---
- hosts: localhost
  gather_facts: no
  vars:
    - dir: /Users/Jgomez/hola


  tasks:

    - name: cat file
      ansible.builtin.shell: "echo 'hola mundo'"
      register: salida

    - debug:
        msg: "{{salida}}"
